"""
Django settings for geodjango project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "top_secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").strip().lower() not in ("0", "false", "no")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        "DJANGO_ALLOWED_HOSTS", "127.0.0.1,137.184.81.85,localhost"
    ).split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'world',
    'django_apscheduler'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise serves the built SPA's static assets in production. Optional in dev
# (Vite serves the SPA and runserver serves static), so only wire it if installed.
try:
    import whitenoise  # noqa: F401

    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
        'whitenoise.middleware.WhiteNoiseMiddleware',
    )
except ImportError:
    pass

ROOT_URLCONF = 'geodjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geodjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'geodjango',
        'USER': 'geo',
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "NAME": os.getenv("DB_NAME", "gis"),
        "USER": os.getenv("DB_USER", "gis"),
        "PASSWORD": os.getenv("DB_PASSWORD", "gis"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv("STATIC_ROOT", str(BASE_DIR / "staticfiles"))

# The built React SPA. In production Django serves its `index.html` (with
# server-injected SEO, see world/seo.py) and WhiteNoise serves the hashed assets.
# Build it with `npm --prefix frontend run build` (Vite `base:/static/`), then
# `manage.py collectstatic`. In dev the SPA is served by Vite instead, so `dist`
# may be absent — only register it as a static dir when it exists.
SPA_DIST = Path(os.getenv("SPA_DIST", str(BASE_DIR.parent / "frontend" / "dist")))
SPA_INDEX_HTML = os.getenv("SPA_INDEX_HTML", str(SPA_DIST / "index.html"))
STATICFILES_DIRS = [SPA_DIST] if SPA_DIST.exists() else []

# User-uploaded media (artwork images, avatars). New uploads go to AWS S3 (see
# below); MEDIA_ROOT still serves any legacy files uploaded before the S3 switch.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media"))

# ── AWS S3 — artist-uploaded images (artwork images + thumbnails, avatars) ────
# Credentials are read from the environment ONLY; never hard-code them (the .env
# is git-ignored). The upload code fails loudly when these are unset rather than
# silently falling back to local disk.
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_REGION = os.getenv("AWS_S3_REGION", "us-east-2")
AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME", "arte-colibri")

# ── OpenRouter (AI SEO generation) ───────────────────────────────────────────
# The API key itself is stored in the DB (curator-managed), not here. These only
# tune the endpoint/model. The model is normally chosen per-key in the dashboard;
# OPENROUTER_MODEL just overrides the code default when a key has none set.
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "")

# Public site base URL (used for OpenRouter attribution headers, etc.).
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "https://artecolibri.mx")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Django REST Framework — the JSON API the React SPA consumes ──────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 8,
}

# ── CORS — the SPA is served from a separate origin in dev (Vite) ────────────
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Role group names used by the curation workflow.
ARTIST_GROUP = "Artist"
CURATOR_GROUP = "Curator"

# ── Reverse proxy (Apache terminates TLS and forwards to gunicorn) ───────────
# Apache sets X-Forwarded-Proto (see deploy/apache/arte-colibri.conf); trusting
# it lets Django know the original request was HTTPS so secure cookies and
# scheme-aware redirects work. CSRF origins are required by Django 4+ for
# cross-checking POSTs (admin/dashboard logins) behind a proxied domain.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# ── Cloudflare Turnstile (bot protection for public forms) ───────────────────
# Empty values disable verification; set both via env (scripts/prod.sh keeps
# them in .env). The site key is public (rendered in the SPA widget); the
# secret key is used server-side against the siteverify endpoint.
TURNSTILE_SITE_KEY = os.getenv("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = os.getenv("TURNSTILE_SECRET_KEY", "")
