# Generated by Django 4.2.30 on 2026-05-27 15:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0000_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('discipline_es', models.CharField(blank=True, default='', max_length=80)),
                ('discipline_en', models.CharField(blank=True, default='', max_length=80)),
                ('bio_es', models.TextField(blank=True, default='')),
                ('bio_en', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('instagram', models.CharField(blank=True, default='', max_length=120)),
                ('web', models.CharField(blank=True, default='', max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artists/avatars/')),
                ('since', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title_es', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('description_es', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('medium_es', models.CharField(blank=True, default='', max_length=200)),
                ('medium_en', models.CharField(blank=True, default='', max_length=200)),
                ('dimensions', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('nfs', 'Not for sale')], default='available', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='world.artist')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_es', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name_es'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label_es', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='world.artwork')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artworks/thumbs/')),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='world.artwork')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='world.tag'),
        ),
        migrations.AddField(
            model_name='artist',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='world.region'),
        ),
        migrations.AddField(
            model_name='artist',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
