# Generated by Django 4.2.30 on 2026-07-04 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('default', 'Site default'), ('home', 'Home'), ('gallery', 'Gallery'), ('artists', 'Artists'), ('locations', 'Browse by location')], max_length=20, unique=True)),
                ('title_es', models.CharField(blank=True, default='', max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('description_es', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('og_title_es', models.CharField(blank=True, default='', max_length=200)),
                ('og_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('og_description_es', models.TextField(blank=True, default='')),
                ('og_description_en', models.TextField(blank=True, default='')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('canonical', models.URLField(blank=True, default='')),
                ('robots', models.CharField(choices=[('index,follow', 'Index, follow'), ('noindex,follow', 'No index, follow'), ('index,nofollow', 'Index, no follow'), ('noindex,nofollow', 'No index, no follow')], default='index,follow', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['key'],
            },
        ),
    ]
