# Generated by Django 4.2.30 on 2026-07-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
