# Generated by Django 4.2.30 on 2026-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_image_s3_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='image_alt_en',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='image_alt_es',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='keywords_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='keywords_es',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
