# Generated by Django 4.2.30 on 2026-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
