# Generated by Django 4.2.30 on 2026-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_artwork_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
